POST {{url}}/chapters
Authorization: {{JWT}}
Accept: application/json
Content-Type:application/json

{
  "title": "The Beginning of the Journey",
  "subtitle": "Setting out into the unknown",
  "content": "This is the main body text of the chapter detailing the adventures and milestones.",
  "startDate": "2026-09-28",
  "endDate": "2026-10-05",
  "visibility": "PRIVATE"
}

###
POST {{url}}/chapters
Authorization: {{JWT}}
Accept: application/json
Content-Type:application/json

{
"title": "Years in china",
"subtitle": "Setting out into the unknown",
"content": "This is the main body text of the chapter detailing the adventures and milestones.",
"startDate": "2026-09-28",
"endDate": "2026-10-05",
"visibility": "PRIVATE"
}

###

GET {{url}}/chapters/1
Authorization:{{JWT}}
Accept: application/json
Content-Type:application/json

###

GET {{url}}/chapters
Authorization:{{JWT}}
Accept: application/json
Content-Type:application/json

###

DELETE localhost:7070/api/chapters/2
Authorization:{{JWT}}
Accept: application/json
Content-Type:application/json

###

PUT localhost:7070/api/chapters/2
Authorization:{{JWT}}
Accept: application/json
Content-Type:application/json

{
  "title": "Updated Title",
  "subtitle": "Updated subtitle",
  "content": "Updated content",
  "visibility": "PUBLIC"
}