POST {{url}}/generatePrompt
Authorization: {{JWT}}
Accept: application/json
Content-Type:application/json

{
  "prompt": "Give me 3 movie titles"
}


###

POST {{url}}/savePrompt
Authorization: {{JWT}}
Accept: application/json
Content-Type:application/json

{
  "content": "This is the response from Gemini that I want to save to the database."
}

