### ==========================================
### GENERATE PROMPT (AI Response Only)
### ==========================================

POST {{url}}/gemini-prompts/generate
Authorization: {{JWT}}
Accept: application/json
Content-Type: application/json

{
  "prompt": "Give me a small prompt about an experience i can write about in my journal"
}

###
POST {{url}}/gemini-prompts/generate
Authorization: {{JWT}}
Accept: application/json
Content-Type: application/json

{
  "prompt": "give me 3 movie titles"
}



###

### ==========================================
### SAVE PROMPT TO DATABASE
### ==========================================

POST {{url}}/gemini-prompts
Authorization: {{JWT}}
Accept: application/json
Content-Type: application/json

{
  "content": "1. Interstellar\n2. 2001: A Space Odyssey\n3. The Martian"
}

###
POST {{url}}/gemini-prompts
Authorization: {{JWT}}
Accept: application/json
Content-Type: application/json

{
  "content": "Write about something from your childhood"
}

###

### ==========================================
### READ PROMPTS
### ==========================================

GET {{url}}/gemini-prompts/1
Authorization: {{JWT}}
Accept: application/json

###

GET {{url}}/gemini-prompts
Authorization: {{JWT}}
Accept: application/json

###

### ==========================================
### DELETE PROMPT
### ==========================================

DELETE {{url}}/gemini-prompts/1
Authorization: {{JWT}}
Accept: application/json